Add `protx` & `verify lock`RPC calls
dashpay/rust-dashcore-rpc pull request #8
Opened 2022-10-20 16:56 UTC by mayoreee

2022-12-21 11:05 UTC, QuantumExplorer requested changes

2022-12-21 11:05 UTC, QuantumExplorer commented on client/src/client.rs
> +    fn get_protx_register_fund(&self, collateral_address: dashcore::Address, ip_and_port: &str, owner_address: dashcore::Address, operator_pub_key: &str, voting_address: dashcore::Address, operator_r
Addressr typo?

2023-01-08 17:49 UTC, mayoreee commented on client/src/client.rs
> +    fn get_protx_register_fund(&self, collateral_address: dashcore::Address, ip_and_port: &str, owner_address: dashcore::Address, operator_pub_key: &str, voting_address: dashcore::Address, operator_r
fixed

2023-01-08 17:52 UTC, QuantumExplorer approved these changes

2023-01-08 17:52 UTC, merged